cam-inc/bento

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/general.md
.github/PULL_REQUEST_TEMPLATE/version.md
CONTRIBUTING.md

一旦 [viron](https://github.com/cam-inc/viron) から持ってきました→Bento Open DocsのRelease Flowを元に修正

Pull Request作成用テンプレート追加

---

examples/nextjs/pages/_app.tsx
examples/nextjs/pages/index.tsx
package-lock.json
packages/core/package.json
packages/core/src/config/index.ts
packages/core/src/editor/index.css.ts
packages/core/src/editor/index.tsx
packages/core/src/helpers/storage/index.ts
packages/core/src/index.ts
packages/core/src/store/index.ts
packages/core/src/theme/index.css.ts
packages/core/src/theme/index.tsx
packages/element-heading/src/editable/index.css.ts
packages/element-heading/src/editable/index.tsx
packages/element-paragraph/src/editable/index.css.ts
packages/element-paragraph/src/editable/index.tsx

Basic Design System

---

turbo.json

core のビルドを待ってからツール類のビルドをするように変更しました
Provide references that relate to your PR, if any.
- https://github.com/vercel/turborepo/discussions/1347

chore: ordered build

---

packages/element-heading/vite.config.ts
packages/element-list/vite.config.ts
packages/element-paragraph/vite.config.ts
packages/text-format/src/toolbar/index.tsx
packages/text-format/vite.config.ts

element-*とtext-*でreact hooksが使えるように。

build: react as external

---

README.md
packages/core/README.md

About Bento Core Package

---

packages/core/README.md

docs: update the section of Terminology

---

CHANGELOG.md
README.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.0.8

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json

chore: bump version v0.0.9

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.0.10

---

examples/nextjs/pages/index.tsx
examples/react/src/App.jsx
packages/core/src/config/index.ts
packages/core/src/editor/index.tsx
packages/core/src/env.d.ts
packages/core/vite.config.ts

update: change returning value form editor with version

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.1.0

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.1.1

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.1.2

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package-lock.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-embed/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.1.3

---

examples/nextjs/package.json
packages/element-paragraph/src/editable/index.tsx

fix: paragraph

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.1.5

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.2.0

---

examples/nextjs/pages/index.tsx
examples/react/src/App.jsx
packages/core/src/config/index.ts
packages/core/src/editor/index.tsx
packages/core/src/plugins/withInsertBreak.ts
packages/core/src/plugins/withInsertSoftBreak.ts
packages/core/src/plugins/withOriginalNormalizeNode.ts
packages/element-note/src/body/index.ts
packages/element-paragraph/src/editable/index.tsx

add default element config
- config props change optional to required
- plugins get config
- editor must has a element

feat: add default element config✨

---

packages/core/src/store/index.ts

- omit defaultElement of the config type to pass the global store

fix: default element type 🐛

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package-lock.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.2.1

---

examples/react/package.json
package-lock.json
packages/core/package.json
packages/core/src/helpers/transform/index.ts
packages/core/src/toolbox/index.tsx
packages/text-emoji/src/editable/index.tsx

- update slate package version
- fix useTransformSetNodes logic
Nan

fix: useTrasformsSetNodes error🐛

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.2.3

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.2.4

---

packages/core/src/portals/popover/index.tsx
packages/core/src/toolbar/index.tsx

toolbarの表示する位置を上に表示するようにしました。
上に余白がなければ、自動でスクロールをします。

feat:change toolbar position :sparkles:

---

packages/core/src/portals/popover/index.tsx
packages/core/src/toolbar/index.tsx

テキスト選択時のツールバーをスクロールに合わせて移動するようにしました。
https://github.com/cam-inc/bento/assets/74893779/28a9e0ef-105d-4cb7-a747-7e32f6912582

feat: toolbar follows scroll

---

packages/core/src/helpers/transform/index.ts

refactor: remove-unnecessary-import

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.3.0

---

packages/core/src/portals/popover/index.tsx
packages/core/src/toolbar/index.tsx

以下の二点のバグを修正しました。
- scrollイベントが発火されない
- editor以外をクリックした時に、ツールバーが消えない
- enterを押した時に、ツールバーを消さないようにする修正は、一旦後回しにしようと思います

fix: fix toolbar behavior

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.3.1

---

package-lock.json
package.json

- update module version in devDependencies

Update module version in devDependencies

---

apps/website/docusaurus.config.js
apps/website/package.json
examples/nextjs-app-router/package.json
examples/nextjs/package.json
package-lock.json
package.json

update dependent modules
Most updates were made with the following commands:
```
npm audit fix
```
However, only the `website` was updated manually.

refactor(): update dependent modules

---

package-lock.json
packages/core/package.json

fixed Incorrect dependency.
Error when installing @bento-editor/core if @bento-editor/jest-presets is included in Dependencies.

fix(@bento-editor/core): Incorrect dependency

---

examples/nextjs-app-router/package.json
examples/nextjs/package.json
package.json
turbo.json

- add clear script
- remove build script in example app

Update npm scripts

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.3.3

---

CHANGELOG.md
apps/website/package.json
examples/nextjs/package.json
examples/react/package.json
package.json
packages/core/package.json
packages/element-callout/package.json
packages/element-divider/package.json
packages/element-heading/package.json
packages/element-link/package.json
packages/element-list/package.json
packages/element-note/package.json
packages/element-paragraph/package.json
packages/element-quote/package.json
packages/element-toggle/package.json
packages/text-emoji/package.json
packages/text-format/package.json

chore: bump version v0.3.4
